Added graceful failure if older versions of DigestUtils is resolved (due to Gradle/Maven) where SHA3 algorithms are not available - therefore catching NoSuchMethodError - ugly but effective.